### PR TITLE
Create UI and navigation

### PR DESCRIPTION
**Pull request by JoonaPeltola**
made some changes to UI and navigation so that they are better
Issue was: Improve user interface usability and navigation #6

### CODE REVIEW

**Comment by JoonaPeltola** [comment]
Improve user interface usability and navigation #6

**Comment by Tuomas-Talkio** [comment]
Good job I approve these changes

**Comment by Tuomas-Talkio** [comment]
Good job I approve these changes

**Comment by konstahakli** [comment]
Very good job!

**Comment by V1ltzu** [comment]
Very good jobba.

**Pull request merged**
